#pragma once

enum fbwl_keybinding_action {
    FBWL_KEYBIND_EXIT,
    FBWL_KEYBIND_EXEC,
    FBWL_KEYBIND_COMMAND_DIALOG,
    FBWL_KEYBIND_FOCUS_NEXT,
    FBWL_KEYBIND_TOGGLE_MAXIMIZE,
    FBWL_KEYBIND_TOGGLE_FULLSCREEN,
    FBWL_KEYBIND_TOGGLE_MINIMIZE,
    FBWL_KEYBIND_WORKSPACE_SWITCH,
    FBWL_KEYBIND_SEND_TO_WORKSPACE,
    FBWL_KEYBIND_TAKE_TO_WORKSPACE,
};
